services:
  mysql-docker:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arthur0702
      MYSQL_DATABASE: shortener
    ports:
      - "3308:3306"
    volumes:
      - mysql_docker_data:/var/lib/mysql

volumes:
  mysql_docker_data:
